In [1]:
import numpy as np 
import pandas as pd 
pd.set_option('display.max_columns', None)
import os

In [2]:
ROOT_PATH = "/kaggle/input/nasa-cmaps/CMaps"
METADATA = ['readme.txt', 'x.txt', 'Damage Propagation Modeling.pdf']
DATA_TXT = []

for file in os.listdir(ROOT_PATH):
    if file not in METADATA:
        DATA_TXT.append(file)
DATA_TXT

['RUL_FD002.txt',
 'test_FD003.txt',
 'train_FD003.txt',
 'test_FD004.txt',
 'train_FD004.txt',
 'test_FD002.txt',
 'train_FD001.txt',
 'train_FD002.txt',
 'RUL_FD001.txt',
 'RUL_FD004.txt',
 'RUL_FD003.txt',
 'test_FD001.txt']

## Merge Train and Test Data into dataframe

In [3]:
train_df = pd.DataFrame()
test_df = pd.DataFrame()
rul_df = pd.DataFrame()

for file in DATA_TXT:
    if 'train' in file:
        df = pd.read_csv(os.path.join(ROOT_PATH, file), sep=' ', header=None)
        df['file_name'] = file
        train_df = pd.concat([train_df, df], axis=0)
    elif 'test' in file:
        df = pd.read_csv(os.path.join(ROOT_PATH, file), sep=' ', header=None)
        # print(df.shape)
        df['file_name'] = file
        test_df = pd.concat([test_df, df], axis=0)
    elif 'RUL' in file:
        df =  pd.read_csv(os.path.join(ROOT_PATH, file), sep=' ', header=None)
        rul_df['file_name'] = file
        rul_df = pd.concat([rul_df, df], axis=0)
        
train_df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,file_name
0,1,1,-0.0005,0.0004,100.0,518.67,642.36,1583.23,1396.84,14.62,21.61,553.97,2387.96,9062.17,1.3,47.30,522.31,2388.01,8145.32,8.4246,0.03,391,2388,100.0,39.11,23.3537,NaN,NaN,train_FD003.txt
1,1,2,0.0008,-0.0003,100.0,518.67,642.50,1584.69,1396.89,14.62,21.61,554.55,2388.00,9061.78,1.3,47.23,522.42,2388.03,8152.85,8.4403,0.03,392,2388,100.0,38.99,23.4491,NaN,NaN,train_FD003.txt
2,1,3,-0.0014,-0.0002,100.0,518.67,642.18,1582.35,1405.61,14.62,21.61,554.43,2388.03,9070.23,1.3,47.22,522.03,2388.00,8150.17,8.3901,0.03,391,2388,100.0,38.85,23.3669,NaN,NaN,train_FD003.txt
3,1,4,-0.0020,0.0001,100.0,518.67,642.92,1585.61,1392.27,14.62,21.61,555.21,2388.00,9064.57,1.3,47.24,522.49,2388.08,8146.56,8.3878,0.03,392,2388,100.0,38.96,23.2951,NaN,NaN,train_FD003.txt
4,1,5,0.0016,0.0000,100.0,518.67,641.68,1588.63,1397.65,14.62,21.61,554.74,2388.04,9076.14,1.3,47.15,522.58,2388.03,8147.80,8.3869,0.03,392,2388,100.0,39.14,23.4583,NaN,NaN,train_FD003.txt

In [4]:
test_df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,file_name
0,1,1,-0.0017,-0.0004,100.0,518.67,641.94,1581.93,1396.93,14.62,21.58,554.56,2387.93,9048.65,1.3,47.09,521.89,2387.94,8133.48,8.3760,0.03,391,2388,100.0,39.07,23.4468,NaN,NaN,test_FD003.txt
1,1,2,0.0006,-0.0002,100.0,518.67,642.02,1584.86,1398.90,14.62,21.58,554.10,2387.94,9046.53,1.3,47.08,521.85,2388.01,8137.44,8.4062,0.03,391,2388,100.0,39.04,23.4807,NaN,NaN,test_FD003.txt
2,1,3,0.0014,-0.0003,100.0,518.67,641.68,1581.78,1391.92,14.62,21.58,554.41,2387.97,9054.92,1.3,47.15,522.10,2387.94,8138.25,8.3553,0.03,391,2388,100.0,39.10,23.4244,NaN,NaN,test_FD003.txt
3,1,4,0.0027,0.0001,100.0,518.67,642.20,1584.53,1395.34,14.62,21.59,554.58,2387.94,9055.04,1.3,47.26,522.45,2387.96,8137.07,8.3709,0.03,392,2388,100.0,38.97,23.4782,NaN,NaN,test_FD003.txt
4,1,5,-0.0001,0.0001,100.0,518.67,642.46,1589.03,1395.86,14.62,21.58,554.16,2388.01,9048.59,1.3,46.94,521.91,2387.97,8134.20,8.4146,0.03,391,2388,100.0,39.09,23.3950,NaN,NaN,test_FD003.txt

In [5]:
rul_df.head(3)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

       file_name      0   1
0  RUL_FD003.txt   18.0 NaN
1  RUL_FD003.txt   79.0 NaN
2  RUL_FD003.txt  106.0 NaN

In [6]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160359 entries, 0 to 53758
Data columns (total 29 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   0          160359 non-null  int64
 1   1          160359 non-null  int64
 2   2          160359 non-null  float64
 3   3          160359 non-null  float64
 4   4          160359 non-null  float64
 5   5          160359 non-null  float64
 6   6          160359 non-null  float64
 7   7          160359 non-null  float64
 8   8          160359 non-null  float64
 9   9          160359 non-null  float64
 10  10         160359 non-null  float64
 11  11         160359 non-null  float64
 12  12         160359 non-null  float64
 13  13         160359 non-null  float64
 14  14         160359 non-null  float64
 15  15         160359 non-null  float64
 16  16         160359 non-null  float64
 17  17         160359 non-null  float64
 18  18         160359 non-null  float64
 19  19         160359 non-null  float64
 20  20         160359 non-null  float64
 21  21         160359 non-null  int64
 22  22         160359 non-null  int64
 23  23         160359 non-null  float64
 24  24         160359 non-null  float64
 25  25         160359 non-null  float64
 26  26         0 non-null       float64
 27  27         0 non-null       float64
 28  file_name  160359 non-null  object
dtypes: float64(24), int64(4), object(1)
memory usage: 36.7+ MB

In [7]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 104897 entries, 0 to 13095
Data columns (total 29 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   0          104897 non-null  int64
 1   1          104897 non-null  int64
 2   2          104897 non-null  float64
 3   3          104897 non-null  float64
 4   4          104897 non-null  float64
 5   5          104897 non-null  float64
 6   6          104897 non-null  float64
 7   7          104897 non-null  float64
 8   8          104897 non-null  float64
 9   9          104897 non-null  float64
 10  10         104897 non-null  float64
 11  11         104897 non-null  float64
 12  12         104897 non-null  float64
 13  13         104897 non-null  float64
 14  14         104897 non-null  float64
 15  15         104897 non-null  float64
 16  16         104897 non-null  float64
 17  17         104897 non-null  float64
 18  18         104897 non-null  float64
 19  19         104897 non-null  float64
 20  20         104897 non-null  float64
 21  21         104897 non-null  int64
 22  22         104897 non-null  int64
 23  23         104897 non-null  float64
 24  24         104897 non-null  float64
 25  25         104897 non-null  float64
 26  26         0 non-null       float64
 27  27         0 non-null       float64
 28  file_name  104897 non-null  object
dtypes: float64(24), int64(4), object(1)
memory usage: 24.0+ MB

In [8]:
train_df = train_df.drop([26, 27], axis='columns')
test_df = test_df.drop([26, 27], axis='columns')
rul_df = rul_df.drop([1], axis='columns')

train_df.shape, test_df.shape

((160359, 27), (104897, 27))

## Making data suitable for training our model

In [9]:
train_df['engine_id'] = train_df['file_name'] + '_' + train_df[0].astype(str)
test_df['engine_id'] = test_df['file_name'] + '_' + test_df[0].astype(str)
train_df['engine_id'].value_counts()

engine_id
train_FD004.txt_118    543
train_FD003.txt_55     525
train_FD003.txt_24     494
train_FD003.txt_96     491
train_FD004.txt_133    489
                      ...
train_FD004.txt_115    131
train_FD002.txt_120    129
train_FD001.txt_39     128
train_FD002.txt_244    128
train_FD004.txt_214    128
Name: count, Length: 709, dtype: int64

In [10]:
test_df['engine_id'].value_counts()

engine_id
test_FD004.txt_25     486
test_FD003.txt_24     475
test_FD004.txt_102    443
test_FD004.txt_135    435
test_FD004.txt_41     414
                     ...
test_FD002.txt_83      21
test_FD004.txt_28      20
test_FD004.txt_229     20
test_FD004.txt_141     19
test_FD004.txt_204     19
Name: count, Length: 707, dtype: int64

In [11]:
learning_window = test_df['engine_id'].value_counts().min()
learning_window

19

**Add RUL for each row in training and testing data**

In [12]:
# train_df[train_df['engine_id'] == 'train_FD004.txt_118']
train_rul = []
for engine_id, cycles in dict(train_df['engine_id'].value_counts()).items():
    temp = list(range(1, cycles+1))
    temp.reverse()
    train_rul += temp

train_df['RUL'] = train_rul
train_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,file_name,engine_id,RUL
0,1,1,-0.0005,0.0004,100.0,518.67,642.36,1583.23,1396.84,14.62,21.61,553.97,2387.96,9062.17,1.3,47.30,522.31,2388.01,8145.32,8.4246,0.03,391,2388,100.0,39.11,23.3537,train_FD003.txt,train_FD003.txt_1,543
1,1,2,0.0008,-0.0003,100.0,518.67,642.50,1584.69,1396.89,14.62,21.61,554.55,2388.00,9061.78,1.3,47.23,522.42,2388.03,8152.85,8.4403,0.03,392,2388,100.0,38.99,23.4491,train_FD003.txt,train_FD003.txt_1,542
2,1,3,-0.0014,-0.0002,100.0,518.67,642.18,1582.35,1405.61,14.62,21.61,554.43,2388.03,9070.23,1.3,47.22,522.03,2388.00,8150.17,8.3901,0.03,391,2388,100.0,38.85,23.3669,train_FD003.txt,train_FD003.txt_1,541
3,1,4,-0.0020,0.0001,100.0,518.67,642.92,1585.61,1392.27,14.62,21.61,555.21,2388.00,9064.57,1.3,47.24,522.49,2388.08,8146.56,8.3878,0.03,392,2388,100.0,38.96,23.2951,train_FD003.txt,train_FD003.txt_1,540
4,1,5,0.0016,0.0000,100.0,518.67,641.68,1588.63,1397.65,14.62,21.61,554.74,2388.04,9076.14,1.3,47.15,522.58,2388.03,8147.80,8.3869,0.03,392,2388,100.0,39.14,23.4583,train_FD003.txt,train_FD003.txt_1,539

In [13]:
test_rul = []
for rul, (engine_id, cycles) in zip(rul_df[0], dict(test_df['engine_id'].value_counts()).items()):
    temp = list(range(1, cycles + 1 + int(rul)))
    temp.reverse()
    test_rul += temp[:cycles]

test_df['RUL'] = test_rul
test_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,file_name,engine_id,RUL
0,1,1,-0.0017,-0.0004,100.0,518.67,641.94,1581.93,1396.93,14.62,21.58,554.56,2387.93,9048.65,1.3,47.09,521.89,2387.94,8133.48,8.3760,0.03,391,2388,100.0,39.07,23.4468,test_FD003.txt,test_FD003.txt_1,504
1,1,2,0.0006,-0.0002,100.0,518.67,642.02,1584.86,1398.90,14.62,21.58,554.10,2387.94,9046.53,1.3,47.08,521.85,2388.01,8137.44,8.4062,0.03,391,2388,100.0,39.04,23.4807,test_FD003.txt,test_FD003.txt_1,503
2,1,3,0.0014,-0.0003,100.0,518.67,641.68,1581.78,1391.92,14.62,21.58,554.41,2387.97,9054.92,1.3,47.15,522.10,2387.94,8138.25,8.3553,0.03,391,2388,100.0,39.10,23.4244,test_FD003.txt,test_FD003.txt_1,502
3,1,4,0.0027,0.0001,100.0,518.67,642.20,1584.53,1395.34,14.62,21.59,554.58,2387.94,9055.04,1.3,47.26,522.45,2387.96,8137.07,8.3709,0.03,392,2388,100.0,38.97,23.4782,test_FD003.txt,test_FD003.txt_1,501
4,1,5,-0.0001,0.0001,100.0,518.67,642.46,1589.03,1395.86,14.62,21.58,554.16,2388.01,9048.59,1.3,46.94,521.91,2387.97,8134.20,8.4146,0.03,391,2388,100.0,39.09,23.3950,test_FD003.txt,test_FD003.txt_1,500

**Divide each engine data while keeping 19 sequences in a single chunk**

In [14]:
from sklearn.preprocessing import LabelEncoder

train_df = train_df.drop(['file_name'], axis='columns')
test_df = test_df.drop(['file_name'], axis='columns')

encoder = LabelEncoder()
train_df['engine_id'] = encoder.fit_transform(train_df['engine_id'])
test_df['engine_id'] = encoder.fit_transform(test_df['engine_id'])

train_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,engine_id,RUL
0,1,1,-0.0005,0.0004,100.0,518.67,642.36,1583.23,1396.84,14.62,21.61,553.97,2387.96,9062.17,1.3,47.30,522.31,2388.01,8145.32,8.4246,0.03,391,2388,100.0,39.11,23.3537,360,543
1,1,2,0.0008,-0.0003,100.0,518.67,642.50,1584.69,1396.89,14.62,21.61,554.55,2388.00,9061.78,1.3,47.23,522.42,2388.03,8152.85,8.4403,0.03,392,2388,100.0,38.99,23.4491,360,542
2,1,3,-0.0014,-0.0002,100.0,518.67,642.18,1582.35,1405.61,14.62,21.61,554.43,2388.03,9070.23,1.3,47.22,522.03,2388.00,8150.17,8.3901,0.03,391,2388,100.0,38.85,23.3669,360,541
3,1,4,-0.0020,0.0001,100.0,518.67,642.92,1585.61,1392.27,14.62,21.61,555.21,2388.00,9064.57,1.3,47.24,522.49,2388.08,8146.56,8.3878,0.03,392,2388,100.0,38.96,23.2951,360,540
4,1,5,0.0016,0.0000,100.0,518.67,641.68,1588.63,1397.65,14.62,21.61,554.74,2388.04,9076.14,1.3,47.15,522.58,2388.03,8147.80,8.3869,0.03,392,2388,100.0,39.14,23.4583,360,539

## Normalizing data

In [15]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

train_df_norm = scaler.fit_transform(train_df.drop(['engine_id', 'RUL', 0, 1], axis='columns'))
train_df_norm = pd.DataFrame(train_df_norm, columns = scaler.get_feature_names_out())
train_df_norm['Cycle_Number'] = train_df[1].values
train_df_norm['engine_id'] = train_df['engine_id'].values
train_df_norm['RUL'] = train_df['RUL'].values

test_df_norm = scaler.transform(test_df.drop(['engine_id', 'RUL', 0, 1], axis='columns'))
test_df_norm = pd.DataFrame(test_df_norm, columns = scaler.get_feature_names_out())
test_df_norm['Cycle_Number'] = test_df[1].values
test_df_norm['engine_id'] = test_df['engine_id'].values
test_df_norm['RUL'] = test_df['RUL'].values

train_df_norm.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,Cycle_Number,engine_id,RUL
0,0.000195,0.001187,1.0,1.0,0.974916,0.910004,0.893110,1.0,1.0,0.961255,0.998565,0.855231,0.948718,0.901521,0.962901,0.993167,0.668706,0.092180,1.0,0.908163,1.0,1.0,0.973764,0.966734,1,360,543
1,0.000226,0.000356,1.0,1.0,0.976193,0.913906,0.893230,1.0,1.0,0.962590,0.998650,0.854922,0.948718,0.895917,0.963170,0.993222,0.685516,0.097574,1.0,0.918367,1.0,1.0,0.969728,0.972051,2,360,542
2,0.000174,0.000475,1.0,1.0,0.973274,0.907653,0.914105,1.0,1.0,0.962314,0.998713,0.861628,0.948718,0.895116,0.962217,0.993139,0.679533,0.080327,1.0,0.908163,1.0,1.0,0.965018,0.967469,3,360,541
3,0.000159,0.000831,1.0,1.0,0.980024,0.916364,0.882170,1.0,1.0,0.964108,0.998650,0.857136,0.948718,0.896717,0.963341,0.993359,0.671474,0.079537,1.0,0.918367,1.0,1.0,0.968718,0.963467,4,360,540
4,0.000245,0.000712,1.0,1.0,0.968713,0.924434,0.895049,1.0,1.0,0.963027,0.998734,0.866318,0.948718,0.889512,0.963561,0.993222,0.674242,0.079228,1.0,0.918367,1.0,1.0,0.974773,0.972564,5,360,539

In [16]:
train_df_norm.shape, train_df.shape, test_df_norm.shape, test_df.shape

((160359, 27), (160359, 28), (104897, 27), (104897, 28))

In [17]:
train_df_norm.index.duplicated().sum(), train_df.index.duplicated().sum()

(0, 99110)

In [18]:
import sys

train_X, test_X = [], []
train_y, test_y = [], []


for i, (engine, cycles) in enumerate(dict(train_df_norm['engine_id'].value_counts(sort=True)).items()):
    sys.stdout.flush()
    print('train df: applying window for engine number = ', i + 1, " out of ", len(train_df['engine_id'].unique()), end="\r")
    train_temp = train_df_norm.drop(['RUL'], axis='columns').astype('float16')
    for i in range(cycles-10):
        
        train_x_temp = np.array(train_temp.iloc[i:i+10])
        train_y_temp = train_df_norm['RUL'].iloc[i + 10]

        train_X.append(train_x_temp)
        train_y.append(train_y_temp)


for i, (engine, cycles) in enumerate(dict(test_df_norm['engine_id'].value_counts(sort=True)).items()):
    sys.stdout.flush()
    print('test_df: applying window for engine number = ', i + 1, " out of ", len(test_df['engine_id'].unique()), end="\r")
    test_temp = test_df_norm.drop(['RUL'], axis='columns').astype('float16')
    for i in range(cycles-10):
        
        test_x_temp = np.array(test_temp.iloc[i:i+10])
        test_y_temp = test_df_norm['RUL'].iloc[i + 10]

        test_X.append(test_x_temp)
        test_y.append(test_y_temp)


train_X = np.array(train_X)
test_X = np.array(test_X)

train_y = np.array(train_y)
test_y = np.array(test_y)

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, LSTM

2025-08-24 17:02:47.435327: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1756054967.588356      19 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1756054967.633455      19 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [20]:

# Get input shape
timesteps = train_X.shape[1]   # e.g. window length
features = train_X.shape[2]    # number of features per timestep

model = Sequential([
    # --- CNN part ---
    Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(timesteps, features)),
    MaxPooling1D(pool_size=2),
    # Dropout(0.3),
    
    # --- LSTM part ---
    LSTM(64, return_sequences=False),
    # Dropout(0.3),
    
    # --- Fully connected ---
    Dense(64, activation='relu'),
    Dense(1)   # output layer → RUL (regression)
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.summary()

# Fit model
history = model.fit(train_X, train_y, 
                    validation_split=0.3,
                    epochs=20, 
                    batch_size=64,
                    verbose=1)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
I0000 00:00:1756054978.736362      19 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15513 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 8, 64)          │         5,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 4, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 64)             │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 42,305 (165.25 KB)

 Trainable params: 42,305 (165.25 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20

I0000 00:00:1756054983.031990      59 cuda_dnn.cc:529] Loaded cuDNN version 90300

1677/1677 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 69485.5391 - mae: 210.0894 - val_loss: 1586.9078 - val_mae: 35.9882
Epoch 2/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5209.7280 - mae: 42.0524 - val_loss: 1388.8666 - val_mae: 28.6612
Epoch 3/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5217.2202 - mae: 40.9027 - val_loss: 1209.0748 - val_mae: 29.6031
Epoch 4/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5136.1128 - mae: 40.3093 - val_loss: 1288.9711 - val_mae: 31.1205
Epoch 5/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5027.5776 - mae: 39.7686 - val_loss: 1270.8156 - val_mae: 30.0036
Epoch 6/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5059.7314 - mae: 39.8827 - val_loss: 1563.2012 - val_mae: 35.2236
Epoch 7/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5057.3496 - mae: 40.0141 - val_loss: 1123.4517 - val_mae: 25.4721
Epoch 8/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 4981.3579 - mae: 39.4601 - val_loss: 921.0933 - val_mae: 22.2706
Epoch 9/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4896.6953 - mae: 38.1289 - val_loss: 1569.8766 - val_mae: 33.4238
Epoch 10/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 4910.0386 - mae: 38.1895 - val_loss: 1328.8478 - val_mae: 30.9024
Epoch 11/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 4917.3076 - mae: 38.1169 - val_loss: 1415.8677 - val_mae: 31.1378
Epoch 12/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4887.4043 - mae: 38.0392 - val_loss: 782.7913 - val_mae: 22.5870
Epoch 13/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4763.8394 - mae: 37.1242 - val_loss: 273.1114 - val_mae: 13.4616
Epoch 14/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 1202.5808 - mae: 16.7244 - val_loss: 15.8295 - val_mae: 3.4019
Epoch 15/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 150.1302 - mae: 6.5595 - val_loss: 7.5946 - val_mae: 2.3577
Epoch 16/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 949.5934 - mae: 10.2386 - val_loss: 8050.4292 - val_mae: 86.8571
Epoch 17/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2853.6687 - mae: 28.6120 - val_loss: 15.4995 - val_mae: 3.3637
Epoch 18/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 308.7121 - mae: 5.9222 - val_loss: 87.0963 - val_mae: 8.8210
Epoch 19/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 853.8564 - mae: 10.3779 - val_loss: 664.1135 - val_mae: 21.1555
Epoch 20/20
1677/1677 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 4624.4263 - mae: 36.9713 - val_loss: 248.7920 - val_mae: 11.6723

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

class Evaluate:
    
    def __init__(self):
        pass
        
    def accuracy(self, y_true, y_pred):
        error = 0
        max_y = max(y_true)
        min_y = min(y_true)
        
        for y_t, y_p in zip(y_true, y_pred):
            error += abs(y_t - y_p)
        
        avg_error = error / len(y_true)
        return 1 - (avg_error / (max_y - min_y))

    def evaluate(self, y_true, y_pred):
        y_true = list(y_true)
        y_pred = list(y_pred)
        accuracy = self.accuracy(y_true, y_pred)
        mse = mean_squared_error(y_true, y_pred)
        mae = mean_absolute_error(y_true, y_pred)
        return {"ACCURACY": accuracy, 'MSE': mse, 'MAE': mae}

In [22]:
y_pred_train = model.predict(train_X).reshape(1, -1)[0]
print("Evaluation on training data: ")
evaluator = Evaluate()
evaluator.evaluate(train_y, y_pred_train)

4790/4790 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Evaluation on training data:

{'ACCURACY': 0.9591832040126013,
 'MSE': 2567.5339753683065,
 'MAE': 21.714535465296105}

In [23]:
y_pred_test = model.predict(test_X).reshape(1, -1)[0]
print("Evaluation on training data: ")
evaluator = Evaluate()
evaluator.evaluate(test_y, y_pred_test)

3058/3058 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step
Evaluation on training data:

{'ACCURACY': 0.9291001843819802,
 'MSE': 3274.4013149235498,
 'MAE': 33.6774124185594}